CREATE DATABASE IF NOT EXISTS ANALYTICS_DB;

CREATE SCHEMA IF NOT EXISTS ANALYTICS_DB.DEV;

CREATE TABLE IF NOT EXISTS ANALYTICS_DB.DEV.CUSTOMERS(
    ID INT,
    NAME STRING,
    CITY STRING,
    SALES NUMBER
);

INSERT INTO ANALYTICS_DB.DEV.CUSTOMERS
VALUES
(1,'SATYA','BBSR',5000),
(2,'AMAN','DELHI',7000),
(3,'RAHUL','MUMBAI',9000);